### ISSUE TITLE
NuGet Package

### ISSUE THREAD

**Issue by CrazyOrange** [pruggitorg/detect-windows-version#4]
Hi, thanks for your research and work!

Have you thought about providing your code via a NuGet package?
I'd love to use it.

Kind regards
CrazyOrange

**Comment by pruggit** [comment]
Thanks for your feedback. I'm considering providing a NugGet package anytime soon.
Cheers,
Stefan

**Comment by pruggit** [comment]
NuGet package is now available [https://www.nuget.org/packages/OSVersionExt/](url)
